#!/bin/bash

start() { echo "Not implemented yet"; RETVAL=1}
stop() { echo "Not implemented yet"; RETVAL=1}
status() { echo "Not implemented yet"; RETVAL=1}
restart() { echo "Not implemented yet"; RETVAL=1}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
