#!/bin/bash
ln -s /usr/lib/<% package_name %>/service/service /etc/init.d/<% package_name %>
rm -rf /usr/lib/<% package_name %>/logs/
mkdir /var/log/<% package_name %>/ /usr/lib/<% package_name %>/logs/
