#!/bin/bash
ln -s /usr/lib/<% PACKAGE_NAME %>/service/service /etc/init.d/<% PACKAGE_NAME %>
rm -rf /usr/lib/<% PACKAGE_NAME %>/logs/
mkdir /var/log/<% PACKAGE_NAME %>/ /usr/lib/<% PACKAGE_NAME %>/logs/
